### ISSUE TITLE
Partial support for Apple silicon

### ISSUE THREAD

**Issue by SquirrelKnight** [imcbrearty/GENIE#20]
I was wondering if you would be able to add partial support for Apple Silicon. I'm fairly new to the world of machine learning, but after a bit of research I found that PyTorch does have support for Apple Silicon (Metal Performance Shaders or mps). Unfortunately, it seems that PyTorch Geometric does not. Do you think it would be at all possible to reconfigure some of the code to be able to take advantage of MPS, or would this be a fruitless task?

I am currently running through the example provided with the code, which has been successfully running on the CPU, but I imagine it would be much faster if I were to take advantage of MPS.

Your response is greatly appreciated!

**Comment by imcbrearty** [comment]
Hi @SquirrelKnight, thanks for your inquiry! That is a good question, and I'm sorry I can't give a better suggestion. I don't know what it would take to make the method compatible with Apply Silicon really. The technique is fairly dependent on PyTorch and PyTorch Geometric, and it would be beyond my skill set to adapt it to support this case. It technically would be possible to implement the model with just "torch_scatter", which might be easier to support, but that would still take a fair amount of code changes. Perhaps it would be possible to run the model in google colab / on the cloud, so that it's less dependent on your local hardware? Though let me know if you find a way to enable support for Apple Silicon, and I can try to add that. Best of luck!

Ian

**Comment by SquirrelKnight** [comment]
Thanks @imcbrearty . Sorry for not getting back to you sooner! I may end up getting some access to enhanced computing cloud resources (with NVIDIA CUDA VRAM), so hopefully that resolves any trouble I have in getting things moving along :)
