### ISSUE TITLE
Assistance with training parameters in train_GENIE_model.py

### ISSUE THREAD

**Issue by sfpoveda** [imcbrearty/GENIE#21]
Hi,

I hope this message finds you well. 

I am reaching out because I am trying to run the train_GENIE_model.py file for a specific zone of interest. However, I am struggling to understand how to modify the training parameters to ensure code functions correctly for my study area. 

From your documentation, I understand that certain training parameters need to be adjusted based on the study area. However, I am finding it challenging to determine  the appropriate values for the parameters `spc_random`, `spc_thresh_rand`, and `dist_range`.

Could you kindly provide any advice or guidance on how to choose these parameters for a specific zone? Your insights would be greatly appreciated.

Thank you for your time and support.

**Comment by imcbrearty** [comment]
Hi, my apologies for the delay. Could you provide a screenshot of your study region + station distribution? To choose those parameters I need a sense of the scale of the region

**Comment by sfpoveda** [comment]
This is one of my study areas and corresponding station distributions (I plan to apply the model to 2-3 other areas as well), all located in Colombia:

![map_sta_dist](https://github.com/user-attachments/assets/fbaae8ea-9d8d-48f3-8621-24c526dcc1a6)

The minimum and maximum distances between stations are 4 meters and 425 km, respectively. Given that seismicity in this area occurs at considerable depths (~150 km) and the area is larger than the example provided, I am using the following grid spacing in X, Y and Z:

`dx: 1000.0`
`dx_depth: 1000.0`

If you can provide further details about the reasoning behind your choices for parameters like `spc_random`, `spc_thresh_rand`, `dist_range`, and any other parameters you consider could be crucial for ensuring the model to work properly I'll be very grateful, as I'll need to adapt this model to other regions as well. Thank you!

**Comment by imcbrearty** [comment]
Thanks for sharing this. You can also edit "d_deg: 0.01" in config (so that it is roughly the same value as dx and dx_depth - since 0.01 degrees is ~1 km).

Basically, the logic behind these parameters is explained in the "Synthethic Training Data" section of the paper. "dist_range" controls the range of possible moveout distances between sources and recievers - roughly, you want the lower end to be low (e.g., 15000; for 15 km), and the upper end to be the maximum possible (e.g., 400000 or 500000, for 400 or 500 km, seems appropriate for your scale). Each source will have a maximum moveout distance sampled from this range of values in dist_range. "spc_random" and "spc_thresh_rand" control how much "randomness" is added per-station on-top of this maximum per-source moveout. That is, rather than use a hard threshold on the maximum distance for each station, for each source it's the value sampled from dist_range, plus a random pertubation for each station sampled from the spc_random and spc_thresh_rand values. This basically emulates the fact that at close to the maximum distance from each source, stations will begin to stochastically miss or detect each event depending on noise levels and attenuation patterns. So these values should be somewhat proportional to the inter-station spacing to make their effect useful. So for your case I think 15000 to 20000 would be reasonable values for these parameters. The difference between spc_random and spc_thresh_rand is just that one effects how different the P and S wave distance thresholds might be compared to one another; spc_thresh_rand > 0 means the P and S wave distance thresholds will be different for each event, which is usually good to use as this can happen in practice. I hope that helps!

**Comment by sfpoveda** [comment]
Thanks for your answer, a very helpful one.

**Comment by imcbrearty** [comment]
No problem!
